export interface ProjectData {
  slug: string;
  title: string;
  client: string;
  location: string;
  venue: string;
  areaSize: string;
  year: string;
  heroImage: string;
  galleryImages: string[];
  challenge: string;
  executionDetails: string;
  results: string;
  category: "Custom Stalls" | "Double Decker" | "Turnkey Solutions" | "3D Renders";
  tag: string;
}

export const projectsData: ProjectData[] = [
  {
    slug: "okaya-power-tech-pavilion",
    title: "Okaya Power Tech Pavilion",
    client: "Okaya Power",
    location: "Pragati Maidan, New Delhi",
    venue: "Pragati Maidan, New Delhi",
    areaSize: "150 sqm",
    year: "2024",
    heroImage: "/images/Designs/1 (1).png",
    galleryImages: [
      "/images/Designs/1 (10).jpeg",
      "/images/Designs/1 (11).jpeg",
      "/images/Designs/1 (12).jpeg",
    ],
    category: "3D Renders",
    tag: "3D Render",
    challenge: "Engineering an ultra-futuristic structural design with massive spans that could support heavy kinetic display elements while keeping structural columns minimal.",
    executionDetails: "Designed utilizing advanced parametric CAD software. The virtual mockup features high-performance LED arches, a suspended tension fabric center disk, and acoustic baffle integration for noise isolation within the pavilion.",
    results: "The render served as a definitive construction blueprint, reducing structural revision cycles by 40% and aligning client expectations perfectly before physical material sourcing.",
  },
  {
    slug: "milton-corporate-appliance-stall",
    title: "Milton Corporate Appliance Stall",
    client: "Milton Appliances",
    location: "BKC Exhibition Centre, Mumbai",
    venue: "BKC Exhibition Centre, Mumbai",
    areaSize: "200 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (2).jpeg",
    galleryImages: [
      "/images/Delivered/1 (8).jpeg",
      "/images/Delivered/1 (9).jpeg",
      "/images/Delivered/1 (10).jpeg",
    ],
    category: "Custom Stalls",
    tag: "Custom Stall",
    challenge: "Accommodating Milton's massive product portfolio in an elegant, non-cluttered layout while ensuring multiple interactive live-cooking and product demo zones were operational.",
    executionDetails: "Fabricated with high-gloss premium acrylic boards, custom CNC-milled display shelves, and integrated warm-white directional spotlights. A dedicated culinary zone was constructed with fire-retardant countertops and hidden exhaust ventilation.",
    results: "Delivered a 200 sqm pristine white culinary island that attracted record footfall, resulting in a 35% increase in B2B lead generation compared to the prior year.",
  },
  {
    slug: "voltas-smart-living-pavilion",
    title: "Voltas Smart Living Pavilion",
    client: "Voltas",
    location: "IICC Dwarka, New Delhi",
    venue: "IICC Dwarka, New Delhi",
    areaSize: "250 sqm",
    year: "2024",
    heroImage: "/images/Designs/1 (2).png",
    galleryImages: [
      "/images/Designs/1 (13).jpeg",
      "/images/Designs/1 (14).jpeg",
      "/images/Designs/1 (15).jpeg",
    ],
    category: "Double Decker",
    tag: "Double Decker",
    challenge: "Building a multi-level structure within rigid trade fair height guidelines while ensuring perfect safety and structural load ratings for upper-level VIP client lounges.",
    executionDetails: "Constructed on a heavy-duty MS structural skeleton wrapped in premium laminate finishes. Featured an elegant cantilevered staircase with glass balustrades and a state-of-the-art climate control system integrated into the lower tier.",
    results: "A commanding double-decker structure that stood out as an architectural highlight at the expo, hosting over 50 VIP partner meetings on the upper level.",
  },
  {
    slug: "livguard-energy-storage-arena",
    title: "Livguard Energy Storage Arena",
    client: "Livguard",
    location: "HITEX, Hyderabad",
    venue: "HITEX, Hyderabad",
    areaSize: "180 sqm",
    year: "2023",
    heroImage: "/images/Designs/51.png",
    galleryImages: [
      "/images/Designs/1 (6).jpeg",
      "/images/Designs/1 (7).jpeg",
      "/images/Designs/1 (8).jpeg",
    ],
    category: "Turnkey Solutions",
    tag: "Turnkey Solution",
    challenge: "Creating a cohesive brand journey that explains complex solar and energy storage systems to both retail consumers and institutional buyers.",
    executionDetails: "Built with clean seamless paint finish, backlit fabric graphics, and high-impact custom color matching. Features interactive touchscreen panels displaying live energy simulations, backed by a dedicated server rack.",
    results: "An award-winning exhibit that simplified energy education, resulting in over 500 catalog downloads and substantial dealer network signups.",
  },
  {
    slug: "procook-culinary-experience-zone",
    title: "ProCook Culinary Experience Zone",
    client: "ProCook",
    location: "BIEC, Bengaluru",
    venue: "BIEC, Bengaluru",
    areaSize: "120 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (3).jpeg",
    galleryImages: [
      "/images/Delivered/1 (11).jpeg",
      "/images/Delivered/1 (12).jpeg",
      "/images/Delivered/1 (13).jpeg",
    ],
    category: "Custom Stalls",
    tag: "Custom Stall",
    challenge: "Designing a functional, high-end commercial-grade kitchen layout inside a temporary exhibition space with tight plumbing and safety constraints.",
    executionDetails: "Utilized waterproof commercial grade ply with anti-scratch laminate. Integrated premium built-in appliances, seamless quartz counter finishes, and specialized overhead warm lighting to make food appear appetizing.",
    results: "Successfully hosted live celebrity chef cooking shows that drew massive crowds, generating high social media buzz and top media coverage.",
  },
  {
    slug: "prayag-bath-fittings-pavilion",
    title: "Prayag Bath Fittings Pavilion",
    client: "Prayag",
    location: "Auto Expo, Greater Noida",
    venue: "Auto Expo, Greater Noida",
    areaSize: "300 sqm",
    year: "2024",
    heroImage: "/images/Designs/52.png",
    galleryImages: [
      "/images/Designs/1 (3).jpeg",
      "/images/Designs/1 (4).jpeg",
      "/images/Designs/1 (5).jpeg",
    ],
    category: "Double Decker",
    tag: "Double Decker",
    challenge: "Integrating heavy-duty working water lines for live shower and faucet product demonstrations inside a massive double-decker framework.",
    executionDetails: "Engineered a bespoke drainage and water recirculation pump system hidden inside raised platforms. Upper floor featured a premium meeting boardroom finished in veneer, overlooking the live-water showcase below.",
    results: "Attracted massive attention due to the live water features, establishing Prayag as a premier technology-driven luxury bath brand at the expo.",
  },
  {
    slug: "federal-bank-trade-show-booth",
    title: "Federal Bank Trade Show Booth",
    client: "Federal Bank",
    location: "Pragati Maidan, New Delhi",
    venue: "Pragati Maidan, New Delhi",
    areaSize: "100 sqm",
    year: "2023",
    heroImage: "/images/Delivered/1 (1).jpeg",
    galleryImages: [
      "/images/Delivered/1 (14).jpeg",
      "/images/Delivered/1 (15).jpeg",
      "/images/Delivered/1 (16).jpeg",
    ],
    category: "Turnkey Solutions",
    tag: "Turnkey Solution",
    challenge: "Creating a high-security, high-trust environment reflecting a banking space, while keeping the layout warm, welcoming, and accessible to general walk-ins.",
    executionDetails: "Structured with premium fabric paneled walls, wood-grain highlights, and frosted-glass meeting cabins. Implemented secure network cable routing for live digital banking kiosks and ATM demonstrations.",
    results: "Maintained a clean, professional banking atmosphere that successfully engaged corporate clients and promoted new digital account sign-ups.",
  },
  {
    slug: "treo-premium-glassware-stall",
    title: "Treo Premium Glassware Stall",
    client: "Treo",
    location: "Jio World Convention Centre, Mumbai",
    venue: "Jio World Convention Centre, Mumbai",
    areaSize: "140 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (6).jpeg",
    galleryImages: [
      "/images/Delivered/1 (17).jpeg",
      "/images/Delivered/1 (18).jpeg",
      "/images/Delivered/1 (19).jpeg",
    ],
    category: "Custom Stalls",
    tag: "Custom Stall",
    challenge: "Safely displaying hundreds of fragile glassware items on illuminated shelving units without creating visual clutter or high breakage risks.",
    executionDetails: "Fabricated custom acrylic display shelves featuring integrated LED edge-lighting. Wall partitions were built using acoustic fabric to absorb sound, creating a quiet and luxurious retail showroom environment.",
    results: "Created a mesmerizing crystal-palace effect that highlighted product clarity and designs, resulting in key distributor inquiries from international buyers.",
  },
  {
    slug: "servo-high-performance-lubricants",
    title: "Servo High-Performance Lubricants",
    client: "Servo",
    location: "Pragati Maidan, New Delhi",
    venue: "Pragati Maidan, New Delhi",
    areaSize: "160 sqm",
    year: "2023",
    heroImage: "/images/Delivered/1 (7).jpeg",
    galleryImages: [
      "/images/Delivered/1 (4).jpeg",
      "/images/Delivered/1 (5).jpeg",
      "/images/Delivered/1 (11).jpeg",
    ],
    category: "Turnkey Solutions",
    tag: "Turnkey Solution",
    challenge: "Creating an immersive industrial experience reflecting Servo's high-tech machinery solutions while maintaining a modern, sustainable brand aesthetic.",
    executionDetails: "Incorporated eco-friendly recycled board structures, high-efficiency low-heat LED fixtures, and vertical green wall installations. Built mock mechanical engine components with neon glow lines for dynamic visuals.",
    results: "Recognized as the greenest stall design at the trade fair, matching Servo's transition to sustainable energy products.",
  },
];
