export interface ProjectData {
  slug: string;
  title: string;
  client: string;
  location: string;
  venue: string;
  areaSize: string;
  year: string;
  heroImage: string;
  galleryImages: string[];
  challenge: string;
  executionDetails: string;
  results: string;
  category: "Custom Stalls" | "Double Decker" | "Turnkey Solutions" | "3D Renders";
  tag: string;
}

export const projectsData: ProjectData[] = [
  {
    slug: "prayag-bath-fittings-pavilion",
    title: "Prayag Bath Fittings Pavilion",
    client: "Prayag",
    location: "Pragati Maidan, New Delhi",
    venue: "Pragati Maidan, New Delhi",
    areaSize: "150 sqm",
    year: "2024",
    heroImage: "/images/Designs/1 (1).png",
    galleryImages: [
      "/images/Designs/1 (10).jpeg",
      "/images/Designs/1 (11).jpeg",
      "/images/Designs/1 (12).jpeg",
    ],
    category: "3D Renders",
    tag: "3D Render",
    challenge: "Integrating heavy-duty working water lines for live shower and faucet product demonstrations inside a high-tech 3D pavilion framework.",
    executionDetails: "Designed utilizing advanced parametric CAD software with water feature simulation. The virtual mockup features high-performance LED arches and illuminated display units.",
    results: "The render served as a definitive construction blueprint, reducing structural revision cycles by 40% and aligning client expectations perfectly.",
  },
  {
    slug: "milton-corporate-appliance-stall",
    title: "Milton Corporate Appliance Stall",
    client: "Milton Appliances",
    location: "BKC Exhibition Centre, Mumbai",
    venue: "BKC Exhibition Centre, Mumbai",
    areaSize: "200 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (2).jpeg",
    galleryImages: [
      "/images/Delivered/1 (8).jpeg",
      "/images/Delivered/1 (9).jpeg",
      "/images/Delivered/1 (10).jpeg",
    ],
    category: "Custom Stalls",
    tag: "Custom Stall",
    challenge: "Accommodating Milton's massive product portfolio in an elegant, non-cluttered layout while ensuring multiple interactive live-cooking and product demo zones were operational.",
    executionDetails: "Fabricated with high-gloss premium acrylic boards, custom CNC-milled display shelves, and integrated warm-white directional spotlights. A dedicated culinary zone was constructed with fire-retardant countertops and hidden exhaust ventilation.",
    results: "Delivered a 200 sqm pristine white culinary island that attracted record footfall, resulting in a 35% increase in B2B lead generation compared to the prior year.",
  },
  {
    slug: "voltas-smart-living-pavilion",
    title: "Voltas Smart Living Pavilion",
    client: "Voltas",
    location: "IICC Dwarka, New Delhi",
    venue: "IICC Dwarka, New Delhi",
    areaSize: "250 sqm",
    year: "2024",
    heroImage: "/images/Designs/1 (2).png",
    galleryImages: [
      "/images/Designs/1 (13).jpeg",
      "/images/Designs/1 (14).jpeg",
      "/images/Designs/1 (15).jpeg",
    ],
    category: "Double Decker",
    tag: "Double Decker",
    challenge: "Building a multi-level structure within rigid trade fair height guidelines while ensuring perfect safety and structural load ratings for upper-level VIP client lounges.",
    executionDetails: "Constructed on a heavy-duty MS structural skeleton wrapped in premium laminate finishes. Featured an elegant cantilevered staircase with glass balustrades and a state-of-the-art climate control system integrated into the lower tier.",
    results: "A commanding double-decker structure that stood out as an architectural highlight at the expo, hosting over 50 VIP partner meetings on the upper level.",
  },
  {
    slug: "lg-electronics-smart-arena",
    title: "LG Electronics Smart Arena",
    client: "LG Electronics",
    location: "HITEX, Hyderabad",
    venue: "HITEX, Hyderabad",
    areaSize: "180 sqm",
    year: "2023",
    heroImage: "/images/Designs/51.png",
    galleryImages: [
      "/images/Designs/1 (6).jpeg",
      "/images/Designs/1 (7).jpeg",
      "/images/Designs/1 (8).jpeg",
    ],
    category: "Turnkey Solutions",
    tag: "Turnkey Solution",
    challenge: "Creating a cohesive consumer and B2B showcase for LG's latest smart home appliances, TV technology, and air conditioning line.",
    executionDetails: "Built with clean seamless paint finish, backlit fabric graphics, and high-impact custom color matching. Features interactive appliance demonstration counters backed by a turnkey structural setup.",
    results: "An award-winning exhibit that simplified appliance technology education, resulting in over 500 catalog downloads and high trade fair engagement.",
  },
  {
    slug: "apcpl-strong-girl-strong-india-stall",
    title: "APCPL Strong Girl Strong India Stall",
    client: "APCPL (IGSTPP)",
    location: "Jio World Convention Centre, Mumbai",
    venue: "Jio World Convention Centre, Mumbai",
    areaSize: "120 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (6).jpeg",
    galleryImages: [
      "/images/Delivered/1 (7).jpeg",
      "/images/Delivered/1 (16).jpeg",
      "/images/Delivered/1 (17).jpeg",
    ],
    category: "Custom Stalls",
    tag: "Custom Stall",
    challenge: "Designing an inspiring, high-impact experiential stall layout with photo cutout boards and brand messaging for APCPL's social empowerment initiative.",
    executionDetails: "Utilized custom CNC cutout character stands, vibrant brand paneling, and elevated stage backdrop elements engineered for high visitor interaction.",
    results: "Generated immense audience engagement and social media photos, amplifying brand reach and campaign awareness.",
  },
  {
    slug: "okaya-power-tech-pavilion",
    title: "Okaya Power Tech Pavilion",
    client: "Okaya Power",
    location: "Auto Expo, Greater Noida",
    venue: "Auto Expo, Greater Noida",
    areaSize: "300 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (9).jpeg",
    galleryImages: [
      "/images/Delivered/1 (3).jpeg",
      "/images/Delivered/1 (4).jpeg",
      "/images/Delivered/1 (5).jpeg",
    ],
    category: "Double Decker",
    tag: "Double Decker",
    challenge: "Engineering a double-decker structural framework to showcase Okaya Power's EV batteries and energy systems.",
    executionDetails: "Constructed with reinforced steel beams, high-gloss brand graphics, and upper-tier VIP meeting rooms overlooking the main exhibition floor.",
    results: "Attracted massive visitor traffic and established Okaya Power as a dominant force in renewable energy storage solutions.",
  },
  {
    slug: "bobcard-32nd-foundation-day-stage",
    title: "BOBCARD 32nd Foundation Day Stage",
    client: "BOBCARD",
    location: "Pragati Maidan, New Delhi",
    venue: "Pragati Maidan, New Delhi",
    areaSize: "100 sqm",
    year: "2023",
    heroImage: "/images/Delivered/1 (1).jpeg",
    galleryImages: [
      "/images/Delivered/1 (14).jpeg",
      "/images/Delivered/1 (15).jpeg",
      "/images/Delivered/1 (16).jpeg",
    ],
    category: "Turnkey Solutions",
    tag: "Turnkey Solution",
    challenge: "Designing and constructing a grand stage & backdrop setup for BOBCARD's 32nd Foundation Day corporate celebration.",
    executionDetails: "Built custom multi-tier LED-lit stage steps, high-definition digital screen surrounds, and decorative ceremony podiums.",
    results: "Delivered a flawless turnkey event backdrop that elevated the brand's corporate milestone celebration.",
  },
  {
    slug: "treo-premium-glassware-stall",
    title: "Treo Premium Glassware Stall",
    client: "Treo",
    location: "Jio World Convention Centre, Mumbai",
    venue: "Jio World Convention Centre, Mumbai",
    areaSize: "140 sqm",
    year: "2024",
    heroImage: "/images/Delivered/1 (6).jpeg",
    galleryImages: [
      "/images/Delivered/1 (17).jpeg",
      "/images/Delivered/1 (18).jpeg",
      "/images/Delivered/1 (19).jpeg",
    ],
    category: "Custom Stalls",
    tag: "Custom Stall",
    challenge: "Safely displaying hundreds of fragile glassware items on illuminated shelving units without creating visual clutter or high breakage risks.",
    executionDetails: "Fabricated custom acrylic display shelves featuring integrated LED edge-lighting. Wall partitions were built using acoustic fabric to absorb sound, creating a quiet and luxurious retail showroom environment.",
    results: "Created a mesmerizing crystal-palace effect that highlighted product clarity and designs, resulting in key distributor inquiries from international buyers.",
  },
  {
    slug: "servo-high-performance-lubricants",
    title: "Servo High-Performance Lubricants",
    client: "Servo",
    location: "Pragati Maidan, New Delhi",
    venue: "Pragati Maidan, New Delhi",
    areaSize: "160 sqm",
    year: "2023",
    heroImage: "/images/Delivered/1 (7).jpeg",
    galleryImages: [
      "/images/Delivered/1 (4).jpeg",
      "/images/Delivered/1 (5).jpeg",
      "/images/Delivered/1 (11).jpeg",
    ],
    category: "Turnkey Solutions",
    tag: "Turnkey Solution",
    challenge: "Creating an immersive industrial experience reflecting Servo's high-tech machinery solutions while maintaining a modern, sustainable brand aesthetic.",
    executionDetails: "Incorporated eco-friendly recycled board structures, high-efficiency low-heat LED fixtures, and vertical green wall installations. Built mock mechanical engine components with neon glow lines for dynamic visuals.",
    results: "Recognized as the greenest stall design at the trade fair, matching Servo's transition to sustainable energy products.",
  },
];
